# Raspberry Pi sensors
- platform: systemmonitor
  resources:
    - type: memory_free
    - type: disk_free
    - type: disk_use_percent
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

